#!/usr/bin/env bash

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create document root and sample pages
mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to add the custom HTTP header
# Use `hostname` command to get the hostname of the server
HOSTNAME=$(hostname)
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=xJJsoquu70o;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart
