#!/usr/bin/env bash
#Configure new HA proxy as a load balancer


# Install HAproxy on a server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy=2.4.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend 27Mikael.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 497074-web-01 54.237.64.95:80
        server 497074-web-02 34.207.64.75:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
    
