#!/usr/bin/env bash
# use while to echo "Best School" 10 times
# echo "Hi" on 9th line

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9  ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((i++))
done